[package]
name = "accumulators"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/dignifiedquire/rust-accumulators"
repository = "https://github.com/dignifiedquire/rust-accumulators"
keywords = []

[dependencies]
num-bigint = { git = "https://github.com/dignifiedquire/num-bigint", features = ["rand", "i128", "u64_digit", "serde", "prime"], package = "num-bigint-dig" }
num-traits = "^0.2.6"
num-integer = "0.1.39"
num-iter = "0.1.37"
rand = "0.6"
failure = "0.1"
failure_derive = "0.1"
blake2 = "0.8.0"
generic-array = "0.12.0"
byteorder = "1.2.7"
bitvec = "0.9.0"

[dependencies.serde]
optional = true
version = "1.0"
default-features = false
features = ["std", "derive"]


[dependencies.classgroup]
optional = true
git = "https://github.com/stichtingorganism/classygroup" 


[dev-dependencies]
criterion = "0.2"
sha2 = "0.8"
rand_chacha = "0.1"


[[bench]]
name = "accumulators_benchmarks"
harness = false


[features]
default = ["rsa_group"]
class_group = ["serde", "classgroup"]
rsa_group = []